"""empty message

Revision ID: 8d34cc86d1c5
Revises: eaa4df30fbc1
Create Date: 2023-01-07 07:07:43.910983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d34cc86d1c5'
down_revision = 'eaa4df30fbc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('task_state_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_state_id', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('project')
    # ### end Alembic commands ###
