"""empty message

Revision ID: dfe05c7891f4
Revises: b46160cc1f11
Create Date: 2023-01-07 07:42:34.070609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe05c7891f4'
down_revision = 'b46160cc1f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('task_project_id_fkey', type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('task_project_id_fkey', 'project', ['project_id'], ['id'])

    # ### end Alembic commands ###
